export const types={

    LOGIN_USER:"LOGIN_USER",
    LOGIN_FAILED:"LOGIN_FAILED",

    CHANGE_NAME:"CHANGE_NAME",
    
    ADD_ROOM:"ADD_ROOM",
    LOAD_ROOM:"LOAD_ROOM",
    ACTIVE_ROOM:"ACTIVE_ROOM",

    START_ADD_MSG:"START_ADD_MSG",
    LOAD_MSG:"LOAD_MSG",
}