export const types={

    START_LOGIN:"START_LOGIN",
    LOGIN_USER:"LOGIN_USER",
    LOGIN_FAILED:"LOGIN_FAILED",
    START_LOGOUT:"START_LOGOUT",
    LOGOUT_USER:"LOGOUT_USER",
    WITHOUT_USER:"WITHOUT_USER",    
    CLEAN_ERRORS:"CLEAN_ERRORS",
    START_REGISTER:"START_REGISTER",
    UPDATE_USER_STATE:"UPDATE_USER_STATE",

    CHANGE_NAME:"CHANGE_NAME",
    
    ADD_ROOM:"ADD_ROOM",
    LOAD_ROOM:"LOAD_ROOM",
    ACTIVE_ROOM:"ACTIVE_ROOM",

    START_ADD_MSG:"START_ADD_MSG",
    LOAD_MSG:"LOAD_MSG",
}